### PR TITLE
Event Community Meeting Autumn 24

### PR DESCRIPTION
**Pull request by mfialaf**
Created an Event for our upcoming Community Event 24 - Autumn edition.

Preview of website:
Komunity_preview

### CODE REVIEW

**Comment by mfialaf** [comment]
@pedrominatel PTAL, it seems that the checks are awaiting approval from a maintainer.

**Review by georgik — CHANGES_REQUESTED** [review]
Please recode all images to webp format.

**Comment by f-hollow** [comment]
> @pedrominatel PTAL, it seems that the checks are awaiting approval from a maintainer.

@mfialaf Actually, this is the reason: [First time outside contributions require maintainer approval to run Actions](https://github.com/renovatebot/renovate/discussions/9865).

**Comment by mfialaf** [comment]
@georgik All should be done

**Review by georgik — APPROVED** [review]

**Pull request merged**
