### PR TITLE
fix: implement feedback to espresso article

### PR DESCRIPTION
**Pull request by f-hollow**
This MR implements feedback from Raffael Rostagno.

- Updated a figure
- Fixed some links

@raffarost Feel free to have another look.

### CODE REVIEW

**Review by pedrominatel — APPROVED** [review]
LGTM

**Comment by raffarost** [comment]
I still don't see the updated image in the article, but that was the only fix needed. Thank you

**Comment by f-hollow** [comment]
> I still don't see the updated image in the article, but that was the only fix needed. Thank you

@raffarost I updated the image. You might not be able to see it because of local cache. I also used this chance and made some other improvements to improve the readability.

I will merge this PR and let's make sure that the image is updated.

**Comment by f-hollow** [comment]
Merged the MR and found that my browser still shows the old picture. Apparently, the issue is that I updated the picture but left the file name the same.

Then I found many similar thread like [this](https://stackoverflow.com/questions/3137934/how-to-clear-browser-cache-when-re-uploading-image-with-same-filename-in-php). Aftetr clearing the browser cache, I see the updated picture.

From now on, I will always be changing file names of updated images.

**Pull request merged**
