### PR TITLE
feat: tabs shortcode

### LINKED ISSUE #66: feat: Add tabs for code snippets
This issue is a request to **add tabs for code snippets**, like [this](https://gohugo.io/contribute/documentation/#site-configuration).

Requirements:

- Add as many tabs as you want
- Name tabs the way you want
- Once a certain tab is chosen, the rest of the tabs on the page should switch to the same tab
- While switching between tabs, the page shouldn't jump up or down
- The tabs should support markdown
- Ideally, the tabs should do code highlighting for specified languages
  ```
  ```c
  ...
  ```

## What I tried

Found two existing shortcodes

- [Code toggles](#user-content-code-toggles) - not exactly what we need
- [Tabs](#user-content-tabs) - exactly what we need
  - Tried to extract the code from the theme but failed due to lack of expertise in javascript, CSS, and HTML

## Code toggles <a href="#user-content-code-toggles" id="code-toggles">#</a>

Code Toggle is implemented in the Hugo docs theme. This shortcode converts given code to `YAML`, `JSON`, and `TOML` formats, then creates a code block with respective tabs.

- Hugo docs: [Site configuration](https://gohugo.io/contribute/documentation/#site-configuration)
  - [Source code](https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/shortcodes/code-toggle.html)
- Design system: [Code Toggle](https://www.engino.co.uk/content-text/code-toggle/)

## Tabs <a href="#user-content-tabs" id="tabs">#</a>

Tabs is implemented in the Learn theme. This is exactly what we need.

- Basic example: [tabs](https://discourse.gohugo.io/t/code-tabs-widget/975/7)
  - Tried using it. The rendered result is 3 separate code snippets, no tabs.
- Tabs [implemented](https://learn.netlify.app/en/shortcodes/tabs/) in the Learn theme
  - [Source code](https://github.com/matcornic/hugo-theme-learn/blob/master/layouts/shortcodes/tabs.html)
  - Tried to extract the code. Identified the files listed below and copied them. Apparently, it is not all the code that _tabs_ has in the theme.

Some files containing the code for _tabs_ are:

- `assets/css/tabs.css`
- `assets/js/jquery-3.3.1.min.js`
- `assets/js/tabs.js`
- `layouts/shortcodes/tab.html`
- `layouts/shortcodes/tabs.html`

## Other resources

Tried both below, but they seem to lack css and javascript files, because I get several code snippets rendered one after another and no tabs.

- [Bootstrap Tabs as Hugo Shortcodes](https://stackoverflow.com/questions/46207512/bootstrap-tabs-as-hugo-shortcodes)
- [hugo-dynamic-tabs](https://github.com/rvanhorn/hugo-dynamic-tabs)

### PR DESCRIPTION
**Pull request by horw**
Hello, in this PR, the tabs functionality from the Learn template was added. You can find more information about it at  https://learn.netlify.app/en/shortcodes/tabs/ 
close #66

### CODE REVIEW

**Comment by horw** [comment]
There is example how it works
image
image
image

**Comment by horw** [comment]
After tests should remove content/blog/zephyr-max-wifi-throughput/index.md

**Comment by f-hollow** [comment]
@georgik PTAL

**Comment by f-hollow** [comment]
@horw All the requirements listed in #66 are fulfilled. Thanks a lot for implementing the tabs, everything works without a hitch!

@georgik merged an article with the following fragment:

---

1. **Clone Sample Project**:

   Let's clone the project and configure `TOOLCHAINS` environment variable with the version of the installed Swift 6.


   - Linux:
   ```bash
   git clone git@github.com:apple/swift-embedded-examples.git --single-branch --branch main
   cd swift-embedded-examples/esp32-led-strip-sdk
   ```

   - macOS
   ```bash
   git clone git@github.com:apple/swift-embedded-examples.git --single-branch --branch main
   #export TOOLCHAINS=org.swift.600202406111a
   export TOOLCHAINS=$(plutil -extract CFBundleIdentifier raw /Library/Developer/Toolchains/swift-latest.xctoolchain/Info.plist)
   cd swift-embedded-examples/esp32-led-strip-sdk
   ```
---

To test the tabs, I tried to place the Linux and macOS code into a tabbed code block. To make the tabbed code block indented as the original code blocks in the article, we need to add 4 spaces before tabs/tab shortcode tags. That is fine. However, we cannot indent the code block content by more that 6-7 spaces, because markdown treats lines preceded with 8 and more spaces as code by default, so the \`\`\`bash and \`\`\` tags become part of the visible code and no highlighting is supported in this case.

All in all, if we want a tabbed code block, we can indent shortcode tags, but we shouldn't indent the content of tabs to retain highlighting for specified languages:

```markdown
1. **Clone Sample Project**:

   Let's clone the project and configure `TOOLCHAINS` environment variable with the version of the installed Swift 6.

    {{< tabs groupId="config" >}}
      {{% tab name="Linux" %}}
  Linux code block
      {{% /tab %}}
      {{% tab name="macOS" %}}
  macOS code block
      {{% /tab %}}
    {{< /tabs >}}
```

This comment describes the issues I came across, but it is not the issue with tabs implementation. It is the markdown's syntax peculiarities. So we should not indent the tab content by more than 6 spaces.

**Comment by igrr** [comment]
> but we shouldn't indent the content of tabs to retain highlighting for specified languages:

Can we automatically un-indent the tab content by the same amount by which the `{{% tab %}}` itself was indented? When we do `{{ $.Parent.Scratch.Add "tabs" (dict "name" $name "content" . ) }}`, can we define a helper function which will unindent `content`?

**Comment by f-hollow** [comment]
> > but we shouldn't indent the content of tabs to retain highlighting for specified languages:
> 
> Can we automatically un-indent the tab content by the same amount by which the `{{% tab %}}` itself was indented? When we do `{{ $.Parent.Scratch.Add "tabs" (dict "name" $name "content" . ) }}`, can we define a helper function which will unindent `content`?

In the same tab, we are quite likely to be adding chunks of content in markdown with varying indentations, such as multi-level lists:

    {{< tabs groupId="config" >}}
      {{% tab name="Linux" %}}
List:

- Item
  - Subitem

    Another paragraph in the subitem.
      {{% /tab %}}
    {{< /tabs >}}
    
In my opinion, writing this content without initial indentations (like above) will result in fewer syntactic errors, as opposed to preceding each line of content with a fixed number of spaces (in this case, 8):

    {{< tabs groupId="config" >}}
      {{% tab name="Linux" %}}
        List:

        - Item
          - Subitem

            Another paragraph in the subitem.
      {{% /tab %}}
    {{< /tabs >}}

The latter fragment looks more appealing from the coding style perspective, but adding the right number of spaces is harder, which increases the likelihood of introducing errors.

I suggest that we try using the tabs as they are for now and revisit Ivan's suggestion later.

**Comment by georgik** [comment]
Nice solutions, works great. One Must be careful about indentation. IMO in case of tabs this is acceptable.
The following snippet works
```
{{< tabs groupId="config" >}}
    {{% tab name="Linux" %}}
Linux code block
```c
#include "c"
int a= 2;
void main() {
    return 0;
}
```
    {{% /tab %}}
    {{% tab name="macOS" %}}
macOS code block
    {{% /tab %}}
{{< /tabs >}}
```

LGTM. Let's merge it on Monday.

**Comment by f-hollow** [comment]
@horw Thank you for your contribution!

Also, thanks to all the reviewers!

I will merge this PR.

**Pull request merged**
